version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building React app...
      - npm run build
      - echo Uploading to S3...
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build