version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
