version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Setting environment variables...
      - export REACT_APP_API_URL=https://d9cppas1tozjn.cloudfront.net
      - export REACT_APP_ENV=production
      - echo "API URL is $REACT_APP_API_URL"
      - echo "Environment is $REACT_APP_ENV"
  build:
    commands:
      - echo Building React app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build